# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoArchiveTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoArchiveTest
  
  pod 'KVOController', '~> 1.2.0'
  

  target 'AutoArchiveTestTests' do
    inherit! :search_paths
    # Pods for testinge
  end

  target 'AutoArchiveTestUITests' do
    # Pods for testing
  end

end
